# AAVE V3 Protocol Configuration
venue: "aave_v3"
type: "defi"

# Canonical instruments available on this venue
canonical_instruments:
  - "aave_v3:aToken:aUSDT"
  - "aave_v3:debtToken:debtUSDT"
  - "aave_v3:aToken:aWETH"
  - "aave_v3:debtToken:debtWETH"
  - "aave_v3:aToken:aweETH"

# Protocol Configuration
network: "ethereum"

