# ML Inference API Configuration
# 
# Configuration for external ML inference API that provides predictions
# for ML-driven trading strategies.
#
# TODO: Set BASIS_ML_API_TOKEN environment variable for live mode

venue_name: "ml_inference_api"
venue_type: "api"
enabled: true

# API endpoints (predictions only - features handled internally)
endpoints:
  predictions: "https://ml-inference-api.example.com/v1/predictions"

# Authentication (environment-specific)
auth:
  type: "bearer_token"
  token_env_var: "BASIS_ML_API_TOKEN"

# Request configuration
request_config:
  timeout_seconds: 30
  retry_attempts: 3
  retry_backoff_seconds: 5
  cache_ttl_seconds: 300  # 5-min cache

# Response validation
validation:
  require_confidence_score: true
  min_confidence: 0.0
  valid_signals: ["long", "short", "neutral", "hold"]

# Supported symbols
supported_symbols:
  - "BTC"
  - "ETH"
  - "USDT"

# API contract
api_contract:
  request_format:
    method: "POST"
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {token}"
    body:
      symbol: "string"  # Trading symbol (e.g., "BTC", "ETH", "USDT")
      timestamp: "string"  # ISO format timestamp
  
  response_format:
    symbol: "string"  # Trading symbol
    timestamp: "string"  # ISO format timestamp
    signal: "string"  # Trading signal (long/short/neutral/hold)
    confidence: "float"  # Signal confidence (0.0 to 1.0)
    stop_loss: "float"  # Stop-loss price
    take_profit: "float"  # Take-profit price
    model_version: "string"  # Model version used

# Example request/response
example:
  request:
    symbol: "BTC"
    timestamp: "2025-01-01T00:00:00Z"
  
  response:
    symbol: "BTC"
    timestamp: "2025-01-01T00:00:00Z"
    signal: "long"
    confidence: 0.85
    stop_loss: 49500.0
    take_profit: 51000.0
    model_version: "v1.2.3"
