# OKX Exchange Configuration
venue: "okx"
type: "cex"

# Canonical instruments available on this venue
canonical_instruments:
  - "okx:BaseToken:USDT"
  - "okx:BaseToken:BTC"
  - "okx:Perp:BTCUSDT"
  - "okx:Perp:ETHUSDT"

# Trading parameters
trading_fees:
  maker: 0.0008  # 0.08% maker fee
  taker: 0.001   # 0.1% taker fee

# Basic limits
max_leverage: 100
min_order_size_usd: 10
min_amount: 10
