# Uniswap DEX Configuration
venue: "uniswap"
type: "infrastructure"

# Protocol Configuration
network: "ethereum"
version: "v3"

# Trading Configuration
min_trade_size_usd: 1
max_slippage_bps: 50  # 0.5%

