services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
      cache_from:
        - deploy-backend:latest
        - deploy-backend:dependencies
        - deploy-backend:builder
      args:
        BUILDKIT_INLINE_CACHE: 1
      target: ""  # Build all stages for caching
    env_file:
      - ../backend/env.unified  # Backend base configuration
      - .env.prod               # Production environment overrides
    depends_on:
      - redis
    ports:
      - "8001:8001"  # Expose backend API port
    volumes:
      - ../data:/app/data
      - ../results:/app/results
      - ../configs:/app/configs:ro
      - ../backend/env.unified:/app/env.unified:ro  # Mount env file as read-only
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: 3s
      retries: 10
    restart: unless-stopped

  caddy:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.caddy-frontend
      cache_from:
        - deploy-caddy:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    env_file:
      - .env.prod   # For Caddy-specific variables (domain, email, auth)
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - ACME_EMAIL=${ACME_EMAIL:-you@example.com}
      - BASIC_AUTH_HASH=${BASIC_AUTH_HASH:-}
    depends_on:
      - backend
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"  # Only used in production
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  # Frontend development service (optional - for testing)
  frontend-dev:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend-test
    ports:
      - "5173:5173"  # Vite dev server port
    volumes:
      - ../frontend:/app
      - /app/node_modules  # Prevent host node_modules from overriding container
    environment:
      - NODE_ENV=dev
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    stdin_open: true
    tty: true
    profiles:
      - frontend-test  # Only start with --profile frontend-test

volumes:
  caddy_data:
  caddy_config:
