# ETH Staking Only Mode Configuration
# ETH unleveraged (no borrowing to stake) staking with LST rewards (staking rewards + seasonal bonuses in ETHFI and EIGEN wrapped up as KING tokens)
# No hedge as ETH share class. we only leverage the staking spread not the overall eth deltas which we keep neutral outside initial + pnl


mode: "eth_staking_only"

# Strategy parameters
lending_enabled: false
staking_enabled: true
basis_trade_enabled: false
  # No borrowing/leverage loops
enable_market_impact: true

# Asset configuration
share_class: "ETH"
asset: "USDT"
lst_type: "weeth"  # or "wsteth"
rewards_mode: "base_eigen"  # base + EIGEN rewards
reserve_ratio: 0.1

# Execution parameters
use_flash_loan: false
unwind_mode: "slow"  # Direct protocol unwinding
hedge_venues: []
hedge_allocation: {}

# Risk parameters (no borrowing, so no LTV)
margin_ratio_target: 1.0  # Not applicable (no CEX margin)
max_stake_spread_move: 0.02215  # Max expected adverse weETH/ETH oracle move (for monitoring)
# NOTE: No AAVE borrowing in this mode, so max_ltv/liquidation_threshold N/A

# Performance targets
target_apy: 0.03  # 3% APY target (just staking)
max_drawdown: 0.01  # 1% max drawdown

# Data requirements
data_requirements:
  - "eth_prices"  # Binance ETH/USDT spot
  - "weeth_prices"  # AAVE oracle prices
  - "aave_lending_rates"  # AAVE rates (weETH, WETH)
  - "staking_rewards"  # Base staking yields
  - "eigen_rewards"  # EIGEN distributions
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model
  - "aave_risk_params"  # AAVE v3 risk parameters JSON

# Live time throttling 
time_throttle_interval: 60


