mode: eth_basis
lending_enabled: false
staking_enabled: false
basis_trade_enabled: true
borrowing_enabled: false
leverage_enabled: false
enable_market_impact: true
share_class: USDT
lst_type: null
rewards_mode: base_only
funding_threshold: 0.0001

position_deviation_threshold: 0.02
margin_ratio_target: 0.8
venues:
  binance:
    venue_type: cex
    instruments:
    - ETH-SPOT
    - ETH-PERP
    order_types:
    - market
    - limit
  bybit:
    venue_type: cex
    instruments:
    - ETH-PERP
    order_types:
    - market
    - limit
  okx:
    venue_type: cex
    instruments:
    - ETH-PERP
    order_types:
    - market
    - limit
  alchemy:
    venue_type: infrastructure
    instruments:
    - WALLET-TRANSFER
    order_types:
    - transfer
data_requirements:
- eth_prices
- eth_futures
- funding_rates
- gas_costs
- execution_costs
time_throttle_interval: 60
target_apy: 0.08
max_drawdown: 0.02
event_logger:
  log_path: ./logs
  log_format: json
  log_level: INFO
  event_categories:
    data:
    - data_loaded
    - data_updated
    - data_error
    risk:
    - risk_breach
    - risk_warning
    - risk_calculation
    event:
    - event_logged
    - event_filtered
    - event_exported
    business:
    - trade_executed
    - position_updated
    - strategy_decision
  event_logging_settings:
    buffer_size: 10000
    export_format: both
    async_logging: true
    compression: false
  log_retention_policy:
    retention_days: 30
    max_file_size_mb: 100
    compression_after_days: 7
  logging_requirements:
    structured_logging: true
    correlation_ids: true
    performance_metrics: true
    error_tracking: true
  event_filtering:
    filter_by_level: true
    filter_by_category: true
    exclude_patterns: []
    include_patterns:
    - '*'
component_config:
  strategy_factory:
    timeout: 30
  strategy_manager:
    actions:
    - entry_full
    - entry_partial
    - exit_full
    - exit_partial
    - sell_dust
    position_calculation:
      hedge_allocation:
        binance: 0.4
        bybit: 0.3
        okx: 0.3
  risk_monitor:
    enabled_risk_types:
    - health_factor
    - ltv_ratio
    - liquidation_threshold
    delta_tracking_asset: ETH
    maintenance_margin_ratio: 0.15
  position_monitor:
    position_subscriptions:
      - "wallet:BaseToken:USDT"
      - "binance:BaseToken:USDT"
      - "binance:BaseToken:ETH"
      - "binance:Perp:ETHUSDT"
      - "bybit:BaseToken:USDT"
      - "bybit:Perp:ETHUSDT"
      - "okx:BaseToken:USDT"
      - "okx:Perp:ETHUSDT"
      - "alchemy:BaseToken:ETH"
    dust_tokens:
      dust_instruments: []
      collection_venues: []
      transfer_venues: []
  pnl_monitor:
    attribution_types: ["funding_pnl", "transaction_costs"]
    reconciliation_tolerance: 0.02
    reporting_currency: "USDT"
  results_store:
    result_types: ["balance_sheet", "pnl_attribution", "risk_metrics", "execution_log"]
    funding_tracking_venues: ["binance", "bybit", "okx"]
    leverage_tracking: false
strategy_config:
  position_deviation_threshold: 0.02
