# ETH Staking Only Mode Configuration
# ETH unleveraged (no borrowing to stake) staking with LST rewards (staking rewards + seasonal bonuses in ETHFI and EIGEN wrapped up as KING tokens)
# No hedge as ETH share class. we only leverage the staking spread not the overall eth deltas which we keep neutral outside initial + pnl


mode: "eth_staking_only"

# Strategy parameters
lending_enabled: false
staking_enabled: true
basis_trade_enabled: false
  # No borrowing/leverage loops
enable_market_impact: true

# Asset configuration
share_class: "ETH"
asset: "USDT"
lst_type: "weeth"  # or "wsteth"
rewards_mode: "base_eigen"  # base + EIGEN rewards
reserve_ratio: 0.1
position_deviation_threshold: 0.02  # 2% deviation from target triggers rebalancing

# Execution parameters
hedge_venues: []
hedge_allocation: {}

# Risk parameters (no borrowing, so no LTV)
margin_ratio_target: 1.0  # Not applicable (no CEX margin)
max_stake_spread_move: 0.02215  # Max expected adverse weETH/ETH oracle move (for monitoring)
# NOTE: No AAVE borrowing in this mode, so max_ltv/liquidation_threshold N/A

# Performance targets
target_apy: 0.03  # 3% APY target (just staking)
max_drawdown: 0.01  # 1% max drawdown

# Data requirements
data_requirements:
  - "eth_prices"  # Binance ETH/USDT spot
  - "weeth_prices"  # AAVE oracle prices
  - "aave_lending_rates"  # AAVE rates (weETH, WETH)
  - "staking_rewards"  # Base staking yields
  - "eigen_rewards"  # EIGEN distributions
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model
  - "aave_risk_params"  # AAVE v3 risk parameters JSON

# Live time throttling 
time_throttle_interval: 60

# Component configuration
component_config:
  risk_monitor:
    enabled_risk_types: []  # No liquidation risk for unleveraged staking
    risk_limits: {}
  
  exposure_monitor:
    exposure_currency: "ETH"
    track_assets: ["ETH", "weETH", "EIGEN", "KING"]
    conversion_methods:
      ETH: "direct"
      weETH: "oracle_price"
      EIGEN: "usd_price"
      KING: "unwrap"
  
  pnl_calculator:
    attribution_types: ["staking_yield_oracle", "staking_yield_rewards", "transaction_costs"]
    reporting_currency: "ETH"
    reconciliation_tolerance: 0.02
  
  strategy_manager:
    strategy_type: "eth_staking_only"
    actions: ["entry_full", "exit_full"]
    rebalancing_triggers: ["deposit", "withdrawal"]
    position_calculation:
      target_position: "eth_staking"
      lst_type: "weeth"
  
  execution_manager:
    supported_actions: ["etherfi_stake", "etherfi_unstake"]
    action_mapping:
      entry_full: ["etherfi_stake"]
      exit_full: ["etherfi_unstake"]
  
  results_store:
    result_types: ["balance_sheet", "pnl_attribution", "execution_log", "dust_tracking"]
    balance_sheet_assets: ["ETH", "weETH", "EIGEN", "KING"]
    pnl_attribution_types: ["staking_yield_oracle", "staking_yield_rewards", "transaction_costs"]
    dust_tracking_tokens: ["EIGEN", "ETHFI", "KING"]
  
  strategy_factory:
    timeout: 30
    max_retries: 3
    validation_strict: true


