# ETH Leveraged Staking Mode Configuration
# ETH leveraged (borrowing to stake) staking with LST rewards (staking rewards + seasonal bonuses in ETHFI and EIGEN wrapped up as KING tokens)
# No hedge as ETH share class. we only leverage the staking spread not the overall eth deltas which we keep neutral outside initial + pnl


mode: "eth_leveraged"

# Strategy parameters
lending_enabled: true
staking_enabled: true
basis_trade_enabled: false
borrowing_enabled: true
  # Enable borrowing for leverage loops
enable_market_impact: true

# Asset configuration
share_class: "ETH"
asset: "ETH"
lst_type: "weeth"  # or "wsteth"
rewards_mode: "base_eigen"  # base + EIGEN rewards
reserve_ratio: 0.1
position_deviation_threshold: 0.02  # 2% deviation from target triggers rebalancing

# Execution parameters
hedge_venues: []
hedge_allocation: {}

# Risk parameters
margin_ratio_target: 1.0  # Target CEX margin ratio (only for USDT share class with hedging)
max_stake_spread_move: 0.02215  # Max expected adverse weETH/ETH oracle move (2.215%)
max_ltv: 0.91  # Maximum LTV for weETH (derived from AAVE risk params)
liquidation_threshold: 0.95  # Liquidation threshold for weETH (derived from AAVE risk params)


# Performance targets
target_apy: 0.20  # 20% APY target (leveraged staking)
max_drawdown: 0.04  # 4% max drawdown

# Data requirements
data_requirements:
  - "eth_prices"  # Binance ETH/USDT spot
  - "weeth_prices"  # AAVE oracle prices
  - "aave_lending_rates"  # AAVE rates (weETH, WETH)
  - "staking_rewards"  # Base staking yields
  - "eigen_rewards"  # EIGEN distributions
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model
  - "aave_risk_params"  # AAVE v3 risk parameters JSON

# Live time throttling 
time_throttle_interval: 60

# REMOVED: capital_allocation - not needed in config, calculated at runtime

# Component configuration
component_config:
  risk_monitor:
    enabled_risk_types: ["ltv_risk", "liquidation_risk"]
    risk_limits:
      target_ltv: 0.9094  # Target LTV = max_ltv * (1 - max_stake_spread_move)
      liquidation_threshold: 0.95
  
  exposure_monitor:
    exposure_currency: "ETH"
    track_assets: ["ETH", "weETH", "aWeETH", "variableDebtWETH", "EIGEN", "KING"]
    conversion_methods:
      ETH: "direct"
      weETH: "oracle_price"
      aWeETH: "aave_index"
      variableDebtWETH: "aave_index"
      EIGEN: "usd_price"
      KING: "unwrap"
  
  pnl_calculator:
    attribution_types: ["supply_yield", "staking_yield_oracle", "staking_yield_rewards", "borrow_costs", "transaction_costs"]
    reporting_currency: "ETH"
    reconciliation_tolerance: 0.02
  
  strategy_manager:
    strategy_type: "eth_leveraged"
    actions: ["entry_full", "entry_partial", "exit_partial", "exit_full", "sell_dust"]
    rebalancing_triggers: ["deposit", "withdrawal", "ltv_drift"]
    position_calculation:
      target_position: "leveraged_eth_staking"
      leverage_ratio: 0.9
      lst_type: "weeth"
  
  execution_manager:
    supported_actions: ["etherfi_stake", "etherfi_unstake", "aave_supply", "aave_borrow", "aave_repay", "sell_dust"]
    action_mapping:
      entry_full: ["etherfi_stake", "aave_supply", "aave_borrow"]
      exit_full: ["aave_repay", "etherfi_unstake"]
      sell_dust: ["sell_dust"]
  
  results_store:
    result_types: ["balance_sheet", "pnl_attribution", "risk_metrics", "execution_log", "leverage_tracking", "dust_tracking"]
    balance_sheet_assets: ["ETH", "weETH", "aWeETH", "variableDebtWETH", "EIGEN", "KING"]
    pnl_attribution_types: ["supply_yield", "staking_yield_oracle", "staking_yield_rewards", "borrow_costs", "transaction_costs"]
    leverage_tracking: true
    dust_tracking_tokens: ["EIGEN", "ETHFI", "KING"]
  
  strategy_factory:
    timeout: 30
    max_retries: 3
    validation_strict: true
