# ETH Basis Trading Mode Configuration
# ETH basis trading strategy with short side hedging in Binance, Bybit, and OKX perps

mode: "eth_basis"

# Strategy parameters
lending_enabled: false
staking_enabled: false
basis_trade_enabled: true
borrowing_enabled: false
# No borrowing/leverage loops
enable_market_impact: true

# Asset configuration
share_class: "ETH"
asset: "ETH"
lst_type: null
rewards_mode: "base_only"

# Execution parameters
use_flash_loan: false
unwind_mode: "fast"
hedge_venues: ["binance", "bybit", "okx"]
hedge_allocation_binance: 0.4
hedge_allocation_bybit: 0.3
hedge_allocation_okx: 0.3
reserve_ratio: 0.1

# Risk parameters
margin_ratio_target: 0.8  # Target CEX margin ratio for futures (80% conservative)
# NOTE: No AAVE in this mode, so no max_ltv/liquidation_threshold/max_stake_spread_move

# Delta neutrality parameters
delta_tolerance: 0.005  # 0.5% tolerance of gross exposure for delta neutrality

# Data requirements
data_requirements:
  - "eth_prices"  # Binance ETH/USDT spot
  - "eth_futures"  # CEX futures data
  - "funding_rates"  # CEX funding rates (all venues)
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model

# Live time throttling 
time_throttle_interval: 60

# Performance targets
target_apy: 0.08  # 8% APY target (funding rate collection)
