# ETH Basis Trading Mode Configuration
# ETH basis trading strategy with short side hedging in Binance, Bybit, and OKX perps

mode: "eth_basis"
strategy_type: "eth_basis"

# Strategy parameters
lending_enabled: false
staking_enabled: false
basis_trade_enabled: true
borrowing_enabled: false
# No borrowing/leverage loops
enable_market_impact: true

# Asset configuration
share_class: "ETH"
asset: "ETH"
lst_type: null
rewards_mode: "base_only"

# Execution parameters
venues:
  binance:
    enabled: true
    max_leverage: 1.0
    min_amount: 0.01
  bybit:
    enabled: true
    max_leverage: 1.0
    min_amount: 0.01
  okx:
    enabled: true
    max_leverage: 1.0
    min_amount: 0.01

hedge_venues: ["binance", "bybit", "okx"]
hedge_allocation_binance: 0.4
hedge_allocation_bybit: 0.3
hedge_allocation_okx: 0.3
reserve_ratio: 0.1
position_deviation_threshold: 0.02  # 2% deviation from target triggers rebalancing

# Risk parameters
margin_ratio_target: 0.8  # Target CEX margin ratio for futures (80% conservative)
max_leverage: 1.0  # Maximum leverage for ETH basis strategy
# NOTE: No AAVE in this mode, so no max_ltv/liquidation_threshold/max_stake_spread_move

# Delta neutrality parameters
delta_tolerance: 0.005  # 0.5% tolerance of gross exposure for delta neutrality

# Data requirements
data_requirements:
  - "eth_prices"  # Binance ETH/USDT spot
  - "eth_futures"  # CEX futures data
  - "funding_rates"  # CEX funding rates (all venues)
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model

# Live time throttling 
time_throttle_interval: 60

# Performance targets
target_apy: 0.08  # 8% APY target (funding rate collection)
max_drawdown: 0.02  # 2% max drawdown (usually positive funding)

# Component configuration
component_config:
  risk_monitor:
    enabled_risk_types: ["cex_margin_ratio", "delta_risk"]
    risk_limits:
      target_margin_ratio: 0.5
      cex_margin_ratio_min: 0.15
      maintenance_margin_requirement: 0.10
      delta_tolerance: 0.005
  
  exposure_monitor:
    exposure_currency: "ETH"
    track_assets: ["ETH", "ETH_PERP"]
    conversion_methods:
      ETH: "direct"
      ETH_PERP: "perp_mark_price"
  
  pnl_calculator:
    attribution_types: ["funding_pnl", "delta_pnl", "basis_pnl", "transaction_costs"]
    reporting_currency: "ETH"
    reconciliation_tolerance: 0.02
  
  strategy_manager:
    strategy_type: "eth_basis"
    actions: ["entry_full", "entry_partial", "exit_partial", "exit_full"]
    rebalancing_triggers: ["deposit", "withdrawal", "delta_drift"]
    position_calculation:
      target_position: "eth_spot_long"
      hedge_position: "eth_perp_short"
      hedge_allocation:
        binance: 0.4
        bybit: 0.3
        okx: 0.3
  
  execution_manager:
    supported_actions: ["cex_spot_buy", "cex_spot_sell", "cex_perp_short", "cex_perp_close"]
    action_mapping:
      entry_full: ["cex_spot_buy", "cex_perp_short"]
      exit_full: ["cex_perp_close", "cex_spot_sell"]
      entry_partial: ["cex_spot_buy", "cex_perp_short"]
      exit_partial: ["cex_perp_close", "cex_spot_sell"]
  
  results_store:
    result_types: ["balance_sheet", "pnl_attribution", "risk_metrics", "execution_log", "delta_tracking"]
    balance_sheet_assets: ["ETH", "ETH_PERP"]
    pnl_attribution_types: ["funding_pnl", "delta_pnl", "basis_pnl", "transaction_costs"]
  
  strategy_factory:
    timeout: 30
    max_retries: 3
    validation_strict: true
