# ML BTC Directional Strategy Configuration
# 
# ML-driven directional BTC strategy with long/short perp trading on 5-min intervals.
# Uses ML predictions for entry/exit signals with take-profit and stop-loss orders.
#
# TODO: ML data files required at data/market_data/ml/ and data/ml_data/predictions/
# TODO: Set BASIS_ML_API_TOKEN environment variable for live mode

mode: "ml_btc_directional"
share_class: "USDT"  # Changed from BTC to USDT (only USDT/ETH supported)
asset: "BTC"
enable_market_impact: true
lending_enabled: false
staking_enabled: false
basis_trade_enabled: false
borrowing_enabled: true  # Required for leverage_enabled
leverage_enabled: true  # Perp futures
max_ltv: 0.8  # Required for borrowing_enabled
rewards_mode: "base_only"  # Required field
reserve_ratio: 0.1  # Required field
position_deviation_threshold: 0.05  # Required field
margin_ratio_target: 0.5  # Required field
target_apy: 0.15  # Required field (15% target for directional strategy)
time_throttle_interval: 300  # Required field (5 minutes)

# ML-specific parameters
ml_config:
  model_registry: "mlflow"
  model_name: "btc_5min_strategy"
  model_version: "production"
  candle_interval: "5min"
  signal_threshold: 0.65  # Min confidence to trade
  max_position_size: 1.0  # 100% of equity

# Execution venues (perp only)
venues:
  binance:
    venue_type: "cex"
    enabled: true
    instruments: ["BTC-PERP"]
    order_types: ["market", "limit", "stop_loss", "take_profit"]

# Data requirements (NO FEATURES - handled externally)
data_requirements:
  - "ml_ohlcv_5min"       # OHLCV 5-min bars
  - "ml_predictions"      # ML signals (long/short/neutral + TP/SL)
  - "btc_usd_prices"      # For PnL calculation
  - "gas_costs"
  - "execution_costs"

# Component configs (mode-agnostic)
component_config:
  position_monitor:
    track_assets: ["BTC", "USDT", "BTC_PERP"]
    initial_balances:
      wallet: {}
      cex_accounts: ["binance"]
      perp_positions: ["binance"]
    fail_on_unknown_asset: true
    
  exposure_monitor:
    exposure_currency: "BTC"
    track_assets: ["BTC", "USDT", "BTC_PERP"]
    conversion_methods:
      BTC: "direct"
      USDT: "usd_price"
      BTC_PERP: "perp_mark_price"
      
  risk_monitor:
    enabled_risk_types: ["cex_margin_ratio", "delta_risk"]
    risk_limits:
      target_margin_ratio: 0.5
      cex_margin_ratio_min: 0.15
      maintenance_margin_requirement: 0.10
      delta_tolerance: 1.0  # 100% delta allowed (directional)
      
  pnl_calculator:
    attribution_types: ["funding_pnl", "price_change_pnl", "transaction_costs"]
    reporting_currency: "BTC"
    reconciliation_tolerance: 0.02
    
  strategy_manager:
    strategy_type: "ml_directional"
    rebalancing_interval: "5min"
    position_deviation_threshold: 0.05
    actions: ["entry_long", "entry_short", "exit_position", "update_stops"]
    rebalancing_triggers: ["ml_signal", "time_interval", "risk_breach"]
    position_calculation:
      method: "ml_signal_based"
      max_position_size: 1.0
      signal_threshold: 0.65
    
  execution_manager:
    supported_actions: ["open_perp_long", "open_perp_short", "close_perp", "update_stop_loss", "update_take_profit"]
    action_mapping:
      open_perp_long: ["binance_perp"]
      open_perp_short: ["binance_perp"]
      close_perp: ["binance_perp"]
      
  results_store:
    result_types: ["pnl", "positions", "trades", "risk_metrics"]
    balance_sheet_assets: ["BTC", "USDT", "BTC_PERP"]
    pnl_attribution_types: ["funding_pnl", "price_change_pnl", "transaction_costs"]
    leverage_tracking: true
    dust_tracking_tokens: []
    
  strategy_factory:
    timeout: 30
    max_retries: 3
    validation_strict: true
