# BTC Directional ML Strategy Configuration (USDT Margin)
# BTC directional strategy with USDT margin/collateral

mode: "ml_btc_directional_usdt_margin"
data_type: "cefi"  # CeFi strategy with ML predictions

# Strategy parameters
lending_enabled: false
staking_enabled: false
basis_trade_enabled: false
borrowing_enabled: true  # Enable borrowing for leverage
leverage_enabled: true  # Enable leverage for USDT margin
enable_market_impact: true

# Asset configuration
share_class: "USDT"
asset: "BTC"
margin_currency: "USDT"  # USDT margin for this variant
lst_type: null

# Risk parameters
margin_ratio_target: 0.8  # Target CEX margin ratio for futures (80% conservative)
max_ltv: 0.75  # Maximum loan-to-value ratio for borrowing

# Venue configuration
venues:
  binance:
    venue_type: "cex"
    enabled: true
    instruments: ["BTC-SPOT", "BTC-PERP"]
    order_types: ["market", "limit"]
  bybit:
    venue_type: "cex"
    enabled: true
    instruments: ["BTC-PERP"]
    order_types: ["market", "limit"]
  okx:
    venue_type: "cex"
    enabled: true
    instruments: ["BTC-PERP"]
    order_types: ["market", "limit"]

# Data requirements
data_requirements:
  - "btc_prices"  # Binance BTC/USDT spot
  - "btc_futures"  # CEX futures data
  - "funding_rates"  # CEX funding rates (all venues)
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model

# Live time throttling 
time_throttle_interval: 60

# Performance targets
target_apy: 0.15  # Used for frontend display and e2e quality gates only
max_drawdown: 0.20  # 20% max drawdown (directional trading)

# Strategy configuration
strategy_config:
  delta_tracking_asset: "USDT"
  position_deviation_threshold: 0.02  # 2% deviation from target triggers rebalancing
  signal_threshold: 0.8  # ML signal confidence threshold
  max_position_size: 1.0
  stop_loss_pct: 0.05
  take_profit_pct: 0.10

# Component configuration
component_config:
  # Position subscriptions
  position_monitor:
    position_subscriptions:
      - "binance:BaseToken:BTC"
      - "binance:Perp:BTCUSDT"
      - "bybit:BaseToken:BTC"
      - "bybit:Perp:BTCUSDT"
      - "okx:BaseToken:BTC"
      - "okx:Perp:BTCUSDT"
    
    # Dust tokens configuration
    dust_tokens:
      dust_instruments: []  # No dust tokens for ML directional
      collection_venues: []
      transfer_venues: []
  
  # Settlement configuration (backtest only)
  settlement:
    funding_enabled: true
    margin_pnl_enabled: false
    seasonal_rewards_enabled: false

  # Risk monitoring
  risk_monitor:
    enabled_risk_types: ["cex_margin_ratio", "delta_risk"]
    delta_tracking_asset: "BTC"
    maintenance_margin_ratio: 0.5
    risk_limits:
      cex_margin_ratio_min: 0.15
      delta_tolerance: 0.005
      liquidation_threshold: 0.95
  
  # Exposure monitoring
  exposure_monitor:
    # No config needed - uses position_subscriptions from position_monitor
    # Always calculates both USD and share_class values
    # Conversions handled by utility_manager
  
  # PnL monitoring
  pnl_monitor:
    attribution_types: ["delta_pnl", "transaction_costs"]
    reconciliation_tolerance: 0.02
    reporting_currency: "USDT"
  
  # Strategy management
  strategy_manager:
    strategy_type: "ml_btc_directional_usdt_margin"
    actions: ["entry_full", "entry_partial", "exit_full", "exit_partial", "sell_dust"]
    position_calculation:
      target_position: "btc_perp_position"
      max_position_size: 1.0
      signal_threshold: 0.8
      stop_loss_pct: 0.05
      take_profit_pct: 0.10
  
  # Execution management
  execution_manager:
    max_retry_attempts: 3
    tight_loop_timeout: 120
    retry_delay_seconds: 0.1
    execution_timeout: 30
    reconciliation_timeout: 10
  
  # Position update handling
  position_update_handler:
    reconciliation_tolerance: 0.01
  
  # Results storage
  results_store:
    result_types: ["balance_sheet", "pnl_attribution", "risk_metrics", "execution_log", "directional_tracking"]
    pnl_attribution_types: ["directional_pnl", "transaction_costs"]
  
  # Strategy factory
  strategy_factory:
    timeout: 30
    max_retries: 3
  
  # Live trading service
  live_trading_service:
    timeout: 3600
    execution_timeout: 30

# ML Configuration
ml_config:
  model_name: "btc_directional_model"
  model_version: "1.0"
  signal_threshold: 0.7
  max_position_size: 1.0
  confidence_threshold: 0.8
  retraining_frequency: "daily"
  feature_importance_threshold: 0.1
  signal_granularity: "5min"
  take_profit_sd: 2
  stop_loss_sd: 2
  sd_floor_bps: 10
  sd_cap_bps: 10

# Event logging configuration
event_logger:
  log_path: "./logs"
  log_format: "json"
  log_level: "INFO"
  event_categories:
    data: ["data_loaded", "data_updated", "data_error"]
    risk: ["risk_breach", "risk_warning", "risk_calculation"]
    event: ["event_logged", "event_filtered", "event_exported"]
    business: ["trade_executed", "position_updated", "strategy_decision"]
  event_logging_settings:
    buffer_size: 10000
    export_format: "both"
    async_logging: true
    compression: false
  log_retention_policy:
    retention_days: 30
    max_file_size_mb: 100
    rotation_frequency: "daily"
    compression_after_days: 7
  logging_requirements:
    structured_logging: true
    correlation_ids: true
    performance_metrics: true
    error_tracking: true
  event_filtering:
    filter_by_level: true
    filter_by_category: true
    exclude_patterns: []
    include_patterns: ["*"]