# Pure Lending Mode Configuration
# Simple lending USDT strategy without leverage or staking or hedging

mode: "pure_lending"

# Strategy parameters
lending_enabled: true
staking_enabled: false
basis_trade_enabled: false
borrowing_enabled: false
  # No borrowing/leverage loops
enable_market_impact: true

# Asset configuration
share_class: "USDT"
asset: "USDT"
lst_type: null
rewards_mode: "base_only"
reserve_ratio: 0.1
position_deviation_threshold: 0.02  # 2% deviation from target triggers rebalancing

# Execution parameters

# Risk parameters
margin_ratio_target: 1.0  # Not applicable (no CEX margin, no borrowing)
# NOTE: No AAVE borrowing in this mode, so no max_ltv/liquidation_threshold/max_stake_spread_move

# Risk Monitor configuration (required by RiskMonitor component)
target_ltv: 0.0  # No borrowing in pure lending mode
max_drawdown: 0.005  # 0.5% max drawdown (only gas/conversion costs)
leverage_enabled: false  # No leverage in pure lending mode

# Venue configuration (required by RiskMonitor component)
venues:
  aave_v3:
    venue: "aave_v3"
    type: "onchain"
    max_leverage: 1.0  # No leverage
    trading_fees: 0.0  # No trading fees for lending

# Data requirements
data_requirements:
  - "usdt_prices"  # USDT/USD spot
  - "aave_lending_rates"  # AAVE rates (USDT)
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model

# Live time throttling 
time_throttle_interval: 60

# REMOVED: capital_allocation - not needed in config, calculated at runtime

# Performance targets
target_apy: 0.05  # 5% APY target
max_drawdown: 0.005  # 0.5% max drawdown (only gas/conversion costs)

