# Pure Lending Mode Configuration
# Simple lending USDT strategy without leverage or staking or hedging

mode: "pure_lending"

# Strategy parameters
lending_enabled: true
staking_enabled: false
basis_trade_enabled: false
borrowing_enabled: false
  # No borrowing/leverage loops
enable_market_impact: true

# Asset configuration
share_class: "USDT"
asset: "USDT"
lst_type: null
rewards_mode: "base_only"
reserve_ratio: 0.1
position_deviation_threshold: 0.02  # 2% deviation from target triggers rebalancing

# Execution parameters
# Venues are handled through separate venue configurations

# Risk parameters
margin_ratio_target: 1.0  # Not applicable (no CEX margin, no borrowing)
leverage_enabled: false  # No leverage in pure lending
max_drawdown: 0.005  # 0.5% max drawdown (only gas/conversion costs)
# NOTE: No AAVE borrowing in this mode, so no max_ltv/liquidation_threshold/max_stake_spread_move

# Data requirements
data_requirements:
  - "usdt_prices"  # USDT/USD spot
  - "aave_lending_rates"  # AAVE rates (USDT)
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model

# Live time throttling 
time_throttle_interval: 60

# REMOVED: capital_allocation - not needed in config, calculated at runtime

# Performance targets
target_apy: 0.05  # 5% APY target

# Component configuration
component_config:
  risk_monitor:
    enabled_risk_types: []  # No liquidation risk for pure lending
    risk_limits: {}
  
  exposure_monitor:
    exposure_currency: "USDT"
    track_assets: ["USDT", "aUSDT"]
    conversion_methods:
      USDT: "direct"
      aUSDT: "aave_index"
  
  pnl_calculator:
    attribution_types: ["supply_yield", "transaction_costs"]
    reporting_currency: "USDT"
    reconciliation_tolerance: 0.02
  
  strategy_manager:
    strategy_type: "pure_lending"
    actions: ["entry_full", "exit_full"]
    rebalancing_triggers: ["deposit", "withdrawal"]
    position_calculation:
      target_position: "aave_usdt_supply"
      max_position: "equity"
  
  execution_manager:
    supported_actions: ["aave_supply", "aave_withdraw"]
    action_mapping:
      entry_full: ["aave_supply"]
      exit_full: ["aave_withdraw"]
  
  results_store:
    result_types: ["balance_sheet", "pnl_attribution", "execution_log"]
    balance_sheet_assets: ["USDT", "aUSDT"]
    pnl_attribution_types: ["supply_yield", "transaction_costs"]
  
  strategy_factory:
    timeout: 30
    max_retries: 3
    validation_strict: true

