# USDT ETH Staking Hedged Simple Strategy Configuration
# USDT share class with ETH simple staking + ETH perp short hedge

mode: "usdt_eth_staking_hedged_simple"
data_type: "defi"  # DeFi strategy with staking

# Strategy parameters
lending_enabled: false
staking_enabled: true
basis_trade_enabled: false
borrowing_enabled: false  # No borrowing for simple staking
leverage_enabled: false
enable_market_impact: true

# Asset configuration
share_class: "USDT"
margin_currency: "USDT"
lst_type: "weETH"  # EtherFi weETH

# Protocol configuration
lending_protocol: "aave_v3"
staking_protocol: "etherfi"

# Position allocation
stake_allocation_percentage: 0.5  # 50% for staking, 50% for hedging

# Risk parameters
margin_ratio_target: 0.5

# Venue configuration
venues:
  etherfi:
    venue_type: "defi"
    instruments: ["weETH"]
    order_types: ["stake", "unstake"]
  binance:
    venue_type: "cex"
    instruments: ["ETH-PERP"]
    order_types: ["market", "limit"]
  bybit:
    venue_type: "cex"
    instruments: ["ETH-PERP"]
    order_types: ["market", "limit"]
  okx:
    venue_type: "cex"
    instruments: ["ETH-PERP"]
    order_types: ["market", "limit"]
  alchemy:
    venue_type: "infrastructure"
    instruments: []
    order_types: []

# Data requirements
data_requirements:
  - "eth_prices"  # ETH/USD price
  - "eth_futures"  # ETH perpetual prices
  - "staking_rates"  # EtherFi staking rates
  - "funding_rates"  # Perpetual funding rates
  - "gas_costs"  # Ethereum gas prices
  - "execution_costs"  # Execution cost model

# Live time throttling 
time_throttle_interval: 60

# Performance targets
target_apy: 0.08  # Used for frontend display and e2e quality gates only
max_drawdown: 0.10  # 10% max drawdown (simple staking)

# Strategy configuration
strategy_config:
  delta_tracking_asset: "ETH"
  position_deviation_threshold: 0.02  # 2% deviation from target triggers rebalancing

# Component configuration
component_config:
  # Position subscriptions
  position_monitor:
    position_subscriptions:
      - "wallet:BaseToken:USDT"
      - "etherfi:BaseToken:weETH"
      - "binance:BaseToken:USDT"
      - "binance:Perp:ETHUSDT"
      - "bybit:BaseToken:USDT"
      - "bybit:Perp:ETHUSDT"
      - "okx:BaseToken:USDT"
      - "okx:Perp:ETHUSDT"
      - "alchemy:BaseToken:ETH"
    
    # Dust tokens configuration
    dust_tokens:
      dust_instruments: 
        - "wallet:BaseToken:EIGEN"
        - "wallet:BaseToken:ETHFI"
        - "binance:BaseToken:EIGEN"
        - "binance:BaseToken:ETHFI"
      collection_venues: ["etherfi", "binance"]
      transfer_venues: ["binance"]  # Convert to USDT
  
  # Settlement configuration (backtest only)
  settlement:
    funding_enabled: true
    margin_pnl_enabled: true
    seasonal_rewards_enabled: true
    seasonal_rewards_frequency: "weekly"  # Mondays at midnight UTC (e.g., EigenLayer)

  # Risk monitoring
  risk_monitor:
    enabled_risk_types: ["health_factor", "ltv_ratio", "liquidation_threshold"]
    delta_tracking_asset: "ETH"
    maintenance_margin_ratio: 0.15
  
  # Exposure monitoring
  exposure_monitor:
    # No config needed - uses position_subscriptions from position_monitor
    # Always calculates both USD and share_class values
    # Conversions handled by utility_manager
  
  # PnL monitoring
  pnl_monitor:
    attribution_types: ["staking_pnl", "transaction_costs", "funding_pnl"]
    reconciliation_tolerance: 0.02
    reporting_currency: "USDT"
  
  # Strategy management
  strategy_manager:
    strategy_type: "usdt_eth_staking_hedged_simple"
    actions: ["entry_full", "entry_partial", "exit_full", "exit_partial", "sell_dust"]
    position_calculation:
      target_position: "weeth_position"
      hedge_allocation:
        binance: 0.4
        bybit: 0.3
        okx: 0.3
  
  # Execution management
  execution_manager:
    max_retry_attempts: 3
    tight_loop_timeout: 120
    retry_delay_seconds: 0.1
    execution_timeout: 30
    reconciliation_timeout: 10
  
  # Position update handling
  position_update_handler:
    reconciliation_tolerance: 0.01
  
  # Results storage
  results_store:
    result_types: ["balance_sheet", "pnl_attribution", "risk_metrics", "execution_log"]
    funding_tracking_venues: ["binance", "bybit", "okx"]
    leverage_tracking: false
  
  # Strategy factory
  strategy_factory:
    timeout: 30
    max_retries: 3
  
  # Live trading service
  live_trading_service:
    timeout: 3600
    execution_timeout: 30

# Event logging configuration
event_logger:
  log_path: "./logs"
  log_format: "json"
  log_level: "INFO"
  event_categories:
    data: ["data_loaded", "data_updated", "data_error"]
    risk: ["risk_breach", "risk_warning", "risk_calculation"]
    event: ["event_logged", "event_filtered", "event_exported"]
    business: ["trade_executed", "position_updated", "strategy_decision"]
  event_logging_settings:
    buffer_size: 10000
    export_format: "both"
    async_logging: true
    compression: false
  log_retention_policy:
    retention_days: 30
    max_file_size_mb: 100
    compression_after_days: 7
  logging_requirements:
    structured_logging: true
    correlation_ids: true
    performance_metrics: true
    error_tracking: true
  event_filtering:
    filter_by_level: true
    filter_by_category: true
    exclude_patterns: []
    include_patterns: ["*"]
