# USDT Stable Share Class Configuration
# USDT-denominated share class for stablecoin strategies

share_class: "USDT"
type: "stable"
description: "USDT stablecoin share class for market neutral strategies"

# Currency Configuration
quote_currency: "USDT"
decimal_places: 6

# Risk Profile
risk_level: "low_to_medium"
market_neutral: true
allows_hedging: true

# Supported Strategies (modes available for this share class)
supported_strategies:
  - "pure_lending_usdt"
  - "btc_basis"
  - "eth_basis"
  - "usdt_eth_staking_hedged_leveraged"
  - "usdt_eth_staking_hedged_simple"
  - "ml_btc_directional_usdt_margin"  # BTC directional on perps, USDT margin

# Share Class Features
leverage_enabled: true
leverage_supported: true
staking_supported: false
basis_trading_supported: true

# Risk Management
max_leverage: 3.0  # Support leverage for hedged strategies
max_drawdown: 0.05  # 5% max drawdown for stable strategies

# Performance targets
target_apy_range:
  min: 0.08  # 8% minimum target APY
  max: 0.15  # 15% maximum target APY
